# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme: minimal-mistakes-jekyll

# Site settings
title:
  en: Contexture | Architecture & Energetics
  fr: Contexture | Architecture & Énergétique

tagline:
  fr: "Conseil et expertise"
  en: "Advice and expertise"

email: info.contexture@gmail.com 

description:
  en: English description of the web
  fr: Description en français

index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://contexture-archi.github.io/" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :nested
