# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site settings
title:
  en: Contexture | Architecture & Energetics
  fr: Contexture | Architecture & Énergétique

tagline:
  fr: "Créativité, rationalité, pluridisciplinarité et conscience professionnelle"
  en: "Créativité, rationalité, pluridisciplinarité et conscience professionnelle"

email: info.contexture@gmail.com

description:
  en: English description of the web
  fr: Description en français

index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://contexture-archi.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :nested

social:
- {icon: 'twitter', link: 'https://twitter.com/ContextureArchi'}
- {icon: 'instagram', link: 'https://www.instagram.com/contextureArchi/'}
- {icon: 'linkedin', link: 'http://be.linkedin.com/pub/helene-montfort/76/294/774'}
- {icon: 'linkedin', link: 'http://be.linkedin.com/pub/jérôme-evrard/51/58a/95b'}
- {icon: 'flickr', link: 'https://www.flickr.com/photos/sharlo1982'}
- {icon: 'envelope', link: 'mailto: info.contexture@gmail.com'}
