title:  "Contexture | Architecture & Énergétique"
tagline: "Conseil et expertise"
description:
author:
  name: "Hélène et Jérôme"
  twitter: contextureArchi

social:
- {icon: 'twitter', link: 'https://twitter.com/ContextureArchi'}
- {icon: 'instagram', link: 'https://www.instagram.com/contextureArchi/'}
- {icon: 'linkedin', link: 'http://be.linkedin.com/pub/helene-montfort/76/294/774'}
- {icon: 'linkedin', link: 'http://be.linkedin.com/pub/jérôme-evrard/51/58a/95b'}
- {icon: 'flickr', link: 'https://www.flickr.com/photos/sharlo1982'}
- {icon: 'envelope', link: 'mailto: info.contexture@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
